In [ ]:
library('tidyverse')
tidyverse_logo()

* __  _    __   .    o           *  .
 / /_(_)__/ /_ ___  _____ _______ ___
/ __/ / _  / // / |/ / -_) __(_-</ -_)
\__/_/\_,_/\_, /|___/\__/_/ /___/\__/
     *  . /___/      o      .       *

In [ ]:
rent = read.csv('D:/Downloads/houses_to_rent.csv')

## câu 1: Đọc dữ liệu, hiển thị thông tin chung của dữ liệu : head(), tail(), str(), summary()

In [ ]:
head(rent)

  X city area rooms bathroom parking.spaces floor animal    furniture
1 0 1    240  3      3       4              NA    acept     furnished
2 1 0     64  2      1       1              10    acept     not furnished
3 2 1    443  5      5       4               3    acept     furnished
4 3 1     73  2     NA       1              12    acept     not furnished
5 4 1     19  1     NA       0              NA    not acept not furnished
6 5 1     13  1     NA       0               2    acept     not furnished
  hoa     rent.amount property.tax fire.insurance total
1 R$0     R$8,000     R$1,000      R$121          R$9,121
2 R$540   R$820       R$122        R$11           R$1,493
3 R$4,172 R$7,000     R$1,417      R$89           R$12,680
4 R$700   R$1,250     R$150        R$16           R$2,116
5 R$0     R$1,200     R$41         R$16           R$1,257
6 R$0     R$2,200     R$42         R$28           R$2,270

In [ ]:
tail(rent)

     X    city area rooms bathroom parking.spaces floor animal    furniture
6075 6074 0     28  1     1        0              NA    not acept furnished
6076 6075 1     50  2     1        1               2    acept     not furnished
6077 6076 1     84  2     2        1              16    not acept furnished
6078 6077 0     48  1     1        0              13    acept     not furnished
6079 6078 1    160  3     2        2              NA    not acept not furnished
6080 6079 1     60  2     1        1               4    acept     furnished
     hoa   rent.amount property.tax fire.insurance total
6075 R$0   R$1,390     R$0          R$18           R$1,408
6076 R$420 R$1,150     R$0          R$15           R$1,585
6077 R$768 R$2,900     R$63         R$37           R$3,768
6078 R$250 R$950       R$42         R$13           R$1,255
6079 R$0   R$3,500     R$250        R$53           R$3,803
6080 R$489 R$1,900     R$0          R$25           R$2,414

In [ ]:
str(rent)

'data.frame':	6080 obs. of  14 variables:
 $ X             : int  0 1 2 3 4 5 6 7 8 9 ...
 $ city          : int  1 0 1 1 1 1 1 1 1 1 ...
 $ area          : int  240 64 443 73 19 13 55 55 82 32 ...
 $ rooms         : int  3 2 5 2 1 1 1 2 3 1 ...
 $ bathroom      : int  3 1 5 NA NA NA NA NA NA NA ...
 $ parking.spaces: int  4 1 4 1 0 0 1 1 1 1 ...
 $ floor         : int  NA 10 3 12 NA 2 2 2 3 16 ...
 $ animal        : Factor w/ 2 levels "acept","not acept": 1 1 1 1 2 1 1 1 1 1 ...
 $ furniture     : Factor w/ 2 levels "furnished","not furnished": 1 2 1 2 2 2 1 2 1 2 ...
 $ hoa           : Factor w/ 1292 levels "Incluso","R$0",..: 2 951 774 1091 2 2 348 1010 1186 944 ...
 $ rent.amount   : Factor w/ 1032 levels "R$1,000","R$1,008",..: 949 980 894 69 55 399 780 84 349 549 ...
 $ property.tax  : Factor w/ 1036 levels "Incluso","R$0",..: 4 227 124 258 621 632 580 838 212 2 ...
 $ fire.insurance: Factor w/ 190 levels "R$10","R$100",..: 24 12 179 62 62 109 151 71 107 121 ...
 $ total         : Factor w/ 4069 levels "R$1,001","R$1,003",..: 3859 236 713 1143 114 1238 3456 499 1664 2015 ...

In [ ]:
summary(rent)

       X             city             area             rooms
 Min.   :   0   Min.   :0.0000   Min.   :   10.0   Min.   : 1.000
 1st Qu.:1520   1st Qu.:1.0000   1st Qu.:   58.0   1st Qu.: 2.000
 Median :3040   Median :1.0000   Median :  100.0   Median : 3.000
 Mean   :3040   Mean   :0.8633   Mean   :  151.2   Mean   : 2.493
 3rd Qu.:4559   3rd Qu.:1.0000   3rd Qu.:  200.0   3rd Qu.: 3.000
 Max.   :6079   Max.   :1.0000   Max.   :24606.0   Max.   :10.000
                                 NA's   :17
    bathroom      parking.spaces       floor              animal
 Min.   : 1.000   Min.   : 0.000   Min.   : 1.000   acept    :4666
 1st Qu.: 1.000   1st Qu.: 1.000   1st Qu.: 3.000   not acept:1414
 Median : 2.000   Median : 1.000   Median : 6.000
 Mean   : 2.347   Mean   : 1.756   Mean   : 7.621
 3rd Qu.: 3.000   3rd Qu.: 2.000   3rd Qu.:11.000
 Max.   :10.000   Max.   :12.000   Max.   :99.000
 NA's   :121                       NA's   :1555
         furniture          hoa         rent.amount    property.tax
 furnished    :1582   R$0     :1291   R$15,000: 155   R$0    :1053
 not furnished:4498   Sem info: 119   R$3,000 : 140   R$84   :  83
                      Incluso :  83   R$3,500 : 135   R$100  :  82
                      R$1,000 :  82   R$2,000 : 132   R$50   :  79
                      R$1,200 :  71   R$2,500 : 127   R$250  :  77
                      R$1,100 :  70   R$1,800 : 124   R$417  :  58
                      (Other) :4364   (Other) :5267   (Other):4648
 fire.insurance     total
 R$23   : 163   R$2,555:  35
 R$26   : 161   R$4,089:  22
 R$16   : 149   R$1,572:   9
 R$39   : 142   R$1,675:   9
 R$20   : 136   R$2,031:   9
 R$32   : 132   R$8,590:   9
 (Other):5197   (Other):5987

## câu 2: đếm số dòng, số cột

In [ ]:
# noi chuoi bang paste
print(paste('number of rows: ', ncol(rent) - 1))
print(paste('number of columns: ', nrow(rent)))

[1] "number of rows:  13"
[1] "number of columns:  6080"

## câu 3: Cho biết 5 loại rooms xuất hiện nhiều nhất trong dataset (5 loại phòng được chọn thuê nhiều nhất)

In [ ]:
x = arrange(
    summarise(
        group_by(rent, rooms), # nhom df rent voi rooms
        room_count = n() # ham chuc nang giong count nhung khong co tham so
    ),
    desc(room_count)
)
head(x, 5)

  rooms room_count
1 3     1994
2 2     1621
3 1     1398
4 4      879
5 5      143

## câu 4: Cho biết các cột có dữ liệu bị thiếu (na). Mỗi cột thiếu bao nhiêu giá trị? Tỷ lệ thiếu (lấy 2 số lẻ)?

In [ ]:
# tao cot, dung ham đem so luong 'na'
count_missings = colSums(is.na(rent))

# tao cot, dung ham round de lam tron 2 chu so, dung ham nrow tinh tong so luong dong
missing_percents = round(count_missings / nrow(rent) * 100, 2)

# tao bang moi
missing_info = data.frame(
  Column = names(count_missings),
  count_missings = count_missings,
  missing_percents = missing_percents
)

# loc gia tri < 0, sap xep giam dan
missing_info = filter(missing_info, count_missings > 0)
arrange(missing_info, desc(count_missings))

  Column   count_missings missing_percents
1 floor    1555           25.58
2 bathroom  121            1.99
3 area       17            0.28

## câu 5: Xóa bỏ các cột property.tax, fire.insurance, total. In head() để xem kết quả.

In [ ]:
rent = select(rent, -property.tax, -fire.insurance, -total)
head(rent)

  X city area rooms bathroom parking.spaces floor animal    furniture
1 0 1    240  3      3       4              NA    acept     furnished
2 1 0     64  2      1       1              10    acept     not furnished
3 2 1    443  5      5       4               3    acept     furnished
4 3 1     73  2     NA       1              12    acept     not furnished
5 4 1     19  1     NA       0              NA    not acept not furnished
6 5 1     13  1     NA       0               2    acept     not furnished
  hoa     rent.amount
1 R$0     R$8,000
2 R$540   R$820
3 R$4,172 R$7,000
4 R$700   R$1,250
5 R$0     R$1,200
6 R$0     R$2,200

## câu 6: Tạo cột rent_amount từ cột rent.amount. Sau đó, bỏ ký tự "R$", và ',' ở rent_amount và đổi dữ liệu của cột này sang kiểu số. In head() để xem kết quả.

In [ ]:
# RegEx [^0-9.]
# gsub
rent = mutate(rent, rent_amount = as.numeric(gsub('[^0-9.]','', rent.amount)))
head(rent)

  X city area rooms bathroom parking.spaces floor animal    furniture
1 0 1    240  3      3       4              NA    acept     furnished
2 1 0     64  2      1       1              10    acept     not furnished
3 2 1    443  5      5       4               3    acept     furnished
4 3 1     73  2     NA       1              12    acept     not furnished
5 4 1     19  1     NA       0              NA    not acept not furnished
6 5 1     13  1     NA       0               2    acept     not furnished
  hoa     rent.amount rent_amount
1 R$0     R$8,000     8000
2 R$540   R$820        820
3 R$4,172 R$7,000     7000
4 R$700   R$1,250     1250
5 R$0     R$1,200     1200
6 R$0     R$2,200     2200

## câu 7: Cho biết bao nhiêu nhà có nội thất, bao nhiêu nhà không có nội thất? Trong nhà có nội thất bao nhiêu nhà cho phép nuôi thú, bao nhiêu nhà không? Trong nhà không có nội thất, bao nhiêu nhà cho phép nuôi thú, bao nhiêu nhà không?

In [ ]:
fur = group_by(rent, furniture)
fur_cnt = summarise(fur, counts = n())
fur_cnt

fur_animal = group_by(rent, furniture, animal)
fur_animal_cnt = summarise(fur_animal, counts = n())
fur_animal_cnt

  furniture     counts
1 furnished     1582
2 not furnished 4498

  furniture     animal    counts
1 furnished     acept     1130
2 furnished     not acept  452
3 not furnished acept     3536
4 not furnished not acept  962